// Manifest of the original placeholder artwork for demo data. Pure module
// (no imports) shared by seed.ts, scripts/build-placeholders.mjs and tests.
//
// The SVGs are generated by `npm run placeholders` into web/public/images/.
// They are original, code-drawn illustrations: no stock photos, no licence or
// attribution needed. Real uploads would replace them later (IMPROVEMENTS P3-2).

export type CoverMotif =
  | "lighthouse" | "vampire-city" | "space-station" | "dragon-forest" | "crown-castle"
  | "harvest" | "industrial-city" | "neon-city" | "dungeon" | "starfall";

/** Game slug → motif + base hue (matches the game's cover_hue). */
export const COVER_ART: Record<string, { motif: CoverMotif; hue: number }> = {
  "mercusuar-di-pulau-kabut": { motif: "lighthouse", hue: 210 },
  "darah-di-balik-tirai-beludru": { motif: "vampire-city", hue: 350 },
  "signal-from-tartarus-station": { motif: "space-station", hue: 160 },
  "naga-naga-hutan-bara-petualangan-pemula": { motif: "dragon-forest", hue: 25 },
  "mahkota-yang-terbelah": { motif: "crown-castle", hue: 45 },
  "panen-harapan": { motif: "harvest", hue: 90 },
  "doskvol-setelah-gelap": { motif: "industrial-city", hue: 200 },
  "neon-run-satu-malam-di-neo-surabaya": { motif: "neon-city", hue: 300 },
  "abomination-vaults": { motif: "dungeon", hue: 130 },
  "starfall-salvage": { motif: "starfall", hue: 260 },
};

export type AvatarStyle =
  | "hood" | "long-hair-flower" | "beanie-goggles" | "hijab"
  | "wizard-hat" | "short-hair" | "curly-hair" | "bun-glasses";

/** Seed GM email → portrait style. */
export const GM_PORTRAITS: Record<string, { key: string; style: AvatarStyle; hue: number; skin: string }> = {
  "gm@questboard.test": { key: "raka", style: "hood", hue: 280, skin: "#c68a5e" },
  "dewi@questboard.test": { key: "dewi", style: "long-hair-flower", hue: 25, skin: "#d9a27a" },
  "bima@questboard.test": { key: "bima", style: "beanie-goggles", hue: 190, skin: "#a86f47" },
  "nadia@questboard.test": { key: "nadia", style: "hijab", hue: 140, skin: "#e0b08a" },
};

export const coverPath = (slug: string) => `/images/covers/${slug}.svg`;
export const portraitPath = (key: string) => `/images/gms/${key}.svg`;

// ── Cover library: one reusable illustration per motif, pickable by any GM ──

/** Order shown in the GM's cover picker, with each motif's palette hue. */
export const COVER_LIBRARY: { motif: CoverMotif; hue: number }[] = [
  { motif: "dragon-forest", hue: 25 },
  { motif: "crown-castle", hue: 45 },
  { motif: "harvest", hue: 90 },
  { motif: "dungeon", hue: 130 },
  { motif: "lighthouse", hue: 210 },
  { motif: "vampire-city", hue: 350 },
  { motif: "industrial-city", hue: 200 },
  { motif: "neon-city", hue: 300 },
  { motif: "space-station", hue: 160 },
  { motif: "starfall", hue: 260 },
];

export const libraryCoverPath = (motif: CoverMotif) => `/images/covers/library/${motif}.svg`;

/**
 * Cover images a GM may save: none (""), any library illustration, or the
 * game's current value (e.g. its bundled demo art). Anything else is rejected,
 * so a crafted request can't point covers at arbitrary URLs.
 */
export function isAllowedCover(value: string, current = ""): boolean {
  if (value === "" || value === current) return true;
  return COVER_LIBRARY.some((c) => libraryCoverPath(c.motif) === value);
}

// ── Portrait library: illustrated avatars any GM can pick instead of initials ──

export type Portrait = { key: string; style: AvatarStyle; hue: number; skin: string };

/** Order shown in the GM's portrait picker. Varied styles and skin tones. */
export const PORTRAIT_LIBRARY: Portrait[] = [
  { key: "wizard-violet", style: "wizard-hat", hue: 260, skin: "#e8b890" },
  { key: "short-blue", style: "short-hair", hue: 210, skin: "#8d5a3b" },
  { key: "curly-rose", style: "curly-hair", hue: 330, skin: "#6b4128" },
  { key: "bun-teal", style: "bun-glasses", hue: 170, skin: "#f0c8a0" },
  { key: "hijab-amber", style: "hijab", hue: 20, skin: "#c68a5e" },
  { key: "beanie-lime", style: "beanie-goggles", hue: 100, skin: "#e0b08a" },
  { key: "flower-magenta", style: "long-hair-flower", hue: 300, skin: "#a86f47" },
  { key: "hood-cyan", style: "hood", hue: 190, skin: "#d9a27a" },
  { key: "short-gold", style: "short-hair", hue: 40, skin: "#f1c9a5" },
  { key: "curly-green", style: "curly-hair", hue: 140, skin: "#c68a5e" },
  { key: "bun-red", style: "bun-glasses", hue: 0, skin: "#8d5a3b" },
  { key: "wizard-olive", style: "wizard-hat", hue: 60, skin: "#a86f47" },
];

export const libraryPortraitPath = (key: string) => `/images/gms/library/${key}.svg`;

/** Portraits a GM may save: none (initials), any library portrait, or their current one. */
export function isAllowedPortrait(value: string, current = ""): boolean {
  if (value === "" || value === current) return true;
  return PORTRAIT_LIBRARY.some((p) => libraryPortraitPath(p.key) === value);
}
