// Builds a tiny icon font from Flaticon UIcons containing only the icons listed
// in src/lib/icons.ts. Output: src/app/icons/{icons.css, *.woff2}.
//
//   npm run icons
//
// Full UIcons fonts are ~350 KB each; the subset is a few KB. The Flaticon
// licence allows modification with attribution (credit link in the site footer).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import subsetFont from "subset-font";
import { REGULAR_ICONS, SOLID_ICONS } from "../src/lib/icons.ts";

const require = createRequire(import.meta.url);
const pkgDir = path.dirname(require.resolve("@flaticon/flaticon-uicons/package.json"));
const outDir = path.join(import.meta.dirname, "..", "src", "app", "icons");
mkdirSync(outDir, { recursive: true });

const STYLES = [
  { prefix: "rr", css: "css/regular/rounded.css", family: "qb-uicons-rr", names: REGULAR_ICONS },
  { prefix: "sr", css: "css/solid/rounded.css", family: "qb-uicons-sr", names: SOLID_ICONS },
];

let out = `/* GENERATED by scripts/build-icons.mjs — do not edit. Icons: UIcons by Flaticon (https://www.flaticon.com/uicons). */\n`;
// In the base layer so Tailwind utilities (hidden, sm:inline-flex, …) can override display.
out += `@layer base{.fi{display:inline-flex;align-items:center;justify-content:center;line-height:1;vertical-align:-0.125em}}\n`;

for (const s of STYLES) {
  const cssPath = path.join(pkgDir, s.css);
  const css = readFileSync(cssPath, "utf8");
  const fontRel = /url\((\.\.\/[^)]+\.woff2)\)/.exec(css)?.[1];
  if (!fontRel) throw new Error(`No woff2 font referenced in ${s.css}`);

  const codepoints = [];
  for (const name of s.names) {
    const m = new RegExp(`\\.fi-${s.prefix}-${name}:before\\{content:"\\\\([0-9a-f]+)"\\}`).exec(css);
    if (!m) throw new Error(`Icon "fi-${s.prefix}-${name}" not found in ${s.css}`);
    codepoints.push([name, m[1]]);
  }

  const text = codepoints.map(([, hex]) => String.fromCodePoint(parseInt(hex, 16))).join("");
  const font = readFileSync(path.resolve(path.dirname(cssPath), fontRel));
  const subset = await subsetFont(font, text, { targetFormat: "woff2" });
  const fontFile = `${s.family}.woff2`;
  writeFileSync(path.join(outDir, fontFile), subset);

  out += `@font-face{font-family:${s.family};src:url(./${fontFile}) format("woff2");font-display:block}\n`;
  out += `[class^="fi-${s.prefix}-"]:before,[class*=" fi-${s.prefix}-"]:before{font-family:${s.family}!important;font-style:normal;font-weight:normal!important;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}\n`;
  for (const [name, hex] of codepoints) out += `.fi-${s.prefix}-${name}:before{content:"\\${hex}"}\n`;
  console.log(`${s.prefix}: ${s.names.length} icons → ${fontFile} (${(subset.length / 1024).toFixed(1)} KB, from ${(font.length / 1024).toFixed(0)} KB)`);
}

writeFileSync(path.join(outDir, "icons.css"), out);
console.log(`Wrote ${path.relative(process.cwd(), path.join(outDir, "icons.css"))}`);
