import type { RegularIcon, SolidIcon } from "@/lib/icons";

type IconProps = { className?: string; label?: string } & (
  | { name: RegularIcon; solid?: false }
  | { name: SolidIcon; solid: true }
);

/**
 * Flaticon UIcons glyph (font subset generated by `npm run icons`).
 * Decorative by default; pass `label` when the icon carries meaning on its own.
 */
export function Icon({ name, solid, className = "", label }: IconProps) {
  return (
    <i
      className={`fi fi-${solid ? "sr" : "rr"}-${name} ${className}`}
      aria-hidden={label ? undefined : true}
      role={label ? "img" : undefined}
      aria-label={label}
    />
  );
}
